'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{planQueue}=require('./queue');
function fixture(){return {agents:[{agent_key:'larissa',status:'active'}],operations:[{id:'op',status:'IN_PROGRESS'}],tasks:[{id:'t',task_key:'TASK-1',status:'READY',priority:90,dependencies:[]}],work_packets:[{packet_key:'WP-1',task_id:'t',operation_id:'op',destination_agent:'larissa',status:'SENT'}]};}
test('selects work without mutating records',()=>{const s=fixture(),original=structuredClone(s);assert.equal(planQueue(s).ready.length,1);assert.deepEqual(s,original);});
test('missing or incomplete dependencies block dispatch',()=>{const s=fixture();s.tasks[0].dependencies=[{task_key:'TASK-2'}];assert.equal(planQueue(s).ready.length,0);s.tasks.push({task_key:'TASK-2',status:'IN_PROGRESS'});assert.equal(planQueue(s).ready.length,0);s.tasks[1].status='DONE';assert.equal(planQueue(s).ready.length,1);});
test('excludes test and completed packets',()=>{const s=fixture();s.work_packets[0].packet_key='WP-TEST-1';assert.equal(planQueue(s).ready.length,0);s.work_packets[0].packet_key='WP-1';s.work_packets[0].status='DONE';assert.equal(planQueue(s).ready.length,0);});
test('never restarts received packets or completed tasks',()=>{for(const mode of ['received','result','task']){const s=fixture();if(mode==='received')s.work_packets[0].received_at='2026-10-08T00:00:00Z';if(mode==='result')s.work_packets[0].result={draft:'x'};if(mode==='task')s.tasks[0].status='DONE';assert.equal(planQueue(s).ready.length,0);}});
test('review routes to Patricia',()=>{const s=fixture();s.work_packets[0].status='REVIEW';const p=planQueue(s);assert.equal(p.ready.length,0);assert.equal(p.review[0].action,'patricia-review');});
test('external actions and approval flags remain blocked',()=>{for(const mode of ['external','approval']){const s=fixture();if(mode==='external')s.work_packets[0].action_scope='external';else s.tasks[0].constraints={approval_required:true};assert.equal(planQueue(s).ready.length,0);}});
test('legacy restriction needs reconciliation',()=>{const s=fixture();s.tasks[0].constraints={execution:'Não executar ainda'};assert.ok(planQueue(s).blocked[0].reasons.includes('constraint-reconciliation-required'));});
test('rejects missing schema and unknown agents',()=>{assert.throws(()=>planQueue({}));const s=fixture();s.work_packets[0].destination_agent='LARISSA_MENDES';assert.equal(planQueue(s).ready.length,0);});
test('paused operation blocks work',()=>{const s=fixture();s.operations[0].status='PAUSED_CAPACITY';assert.equal(planQueue(s).ready.length,0);});
test('agent permission blocks classified external work',()=>{const s=fixture();s.agents[0].permissions={external_contact:false};s.work_packets[0].action_type='contact';assert.ok(planQueue(s).blocked[0].reasons.includes('agent-permission-denied'));});
test('external language without classification fails closed',()=>{const s=fixture();s.work_packets[0].objective='Contatar prospects e enviar mensagem';assert.ok(planQueue(s).blocked[0].reasons.includes('action-classification-required'));});
